services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    platform: linux/amd64
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password123"
    ports:
      - 1433:1433
    volumes:
      - sql_data_volume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password123 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  sql_data_volume:
    driver: local